scipy-conference/scipy_proceedings

README.md
=> replaced 2014 with 2015

README.md, review_criteria.md
At the suggestion of @jaberg , I wrote a quick draft of possible suggested review criteria for scipy to assist the authors and reviewers of full papers for the proceedings. 
I honestly didn't put a lot of original thought into this. Rather, I looked at [what IEEE requires](http://www.ieee.org/conferences_events/conferences/publishing/paper_acceptance_criteria.pdf) and thought about what I personally think I would like SciPy papers to strive for. I wrote those things down in this document. 
As was noted by @jaberg , this is important, actually, as these review criteria could, in part, set forth a potentially long-term tone and a flavor for SciPy. Previously, to my knowledge, we have allowed the reviewers to almost entirely set their own review parameters, which was confusing for all …
=> first draft of review criteria.

publisher/build_paper.py, publisher/writer/__init__.py
The second solution totally worked once I switched the arguments of the line
```
git checkout -- 2015 publisher/build_paper.py publisher/writer/__init__.py
```
to 
```
git checkout 2015 -- publisher/build_paper.py publisher/writer/__init__.py
```
And it looks like the merge is catching the right differences. 
Thanks @katyhuff for writing that code making my life much easier!
=> adds publisher changes to support bibtex in rst files as their own thing

publisher/writer/__init__.py
should fix issue just pointed out in #144  by @philippjfr
=> should fix double mentioning of the equal authors footnote.

papers/howard_bushouse/howard_bushouse.rst
[Edit by jaberg] http://nipy.bic.berkeley.edu:5000/download/25
=> Paper: The James Webb Space Telescope Data Calibration Pipeline (Bushouse)

papers/ankur_ankan/ankur_ankan.rst
=> Paper: pgmpy: Probabilistic Graphical Models using Python (Ankan & Panda)

papers/ian_henriksen/cython_blas_lapack_api.rst
Here's a draft of my proceedings paper. Thanks for the help putting this together!
[Edit by jaberg] Paperbot: http://nipy.bic.berkeley.edu:5000/download/4
=> Paper: Circumventing The Linker: Using SciPy's BLAS and LAPACK Within Cython (Henriksen)

papers/00_intro/intro.rst
@katyhuff Here are my edits to the intro. Sorry it took me so long. I lost the commit history, but branching directly off yours had a lot of extraneous commits.
Happy to comment on changes here.
=> A few edits to intro

papers/jacqueline_kazil/mesa_abm.rst
fixes scipy-conference/scipy_proceedings#174
=> Datacollector to datacollection

papers/jacqueline_kazil/mesa_abm.rst
=> [mesa] Added grid and torus for data collection model

README.md, review_criteria.md
I was thinking these changes should get migrated to master so that people who land on the page see up to date info.
Sorry Stefan, I'm sure you are also great and wonderful but Katy helped us set up the server this year :)
=> Updating README and links for 2016

README.md
Based on the conference website and email sent out, I believe the 2016 papers are due on May 30th. Not sure about the review period end date, though.
=> updated paper deadline for 2016

.gitignore, papers/mikejordan_pacersuchow/mybib.bib, papers/mikejordan_pacersuchow/proselint_2016.rst, publisher/build_paper.py
Resolving merge conflicts from https://github.com/scipy-conference/scipy_proceedings/pull/210
=> Proselint 2016 rb

.gitignore, papers/mikejordan_pacersuchow/mybib.bib, papers/mikejordan_pacersuchow/proselint_2016.rst, publisher/build_paper.py
Here is our submission. Not quite as polished as I'd like, but it'll do for now.
=> Paper: Proselint 2016

README.md, publisher/_templates/article.html.tmpl, publisher/writer/__init__.py
I fixed a couple of straggling grammatical issues in the readme leftover from last year. Also, adjusted the tentative approximate timeline.
=> minor grammatical issues 

README.md, publisher/build_paper.py, publisher/build_papers.py, publisher/build_template.py, publisher/conf.py, publisher/options.py, publisher/tempita/__init__.py, publisher/tests/test_options.py, publisher/writer/__init__.py, requirements.txt
Should close #254, also should make python2/3 support complete.
=> Infrastructure

README.md
this callout was unneccessary. I think it was added last year by unnecessarily grateful proceedings chairs
=> this callout in the readme was unneccessary.

publisher/writer/__init__.py
=> improve error handling for docutils that aren't  0.12

README.md
as discussed in call. pushes things about a week (ish.)
=> updates timeline

papers/horea-ioan_ioanas/paper.rst
As mentioned on Slack @stefanv
=> Typos and minor style improvements

papers/scott_sievert/next.rst
I'm not sure if this will be done later, but I want to make sure the correct link is in place.
=> Links to video for NEXT

publisher/doitools.py, publisher/xreftools.py
Adds module, class, and function docstrings to xreftools and doitools.
=> DOC: inline docs for tools modules

README.md, publisher/build_papers.py, publisher/options.py, publisher/writer/__init__.py, requirements.txt
The set_table_style api was borked with 0.13… it expects a string, but
then iterates over it as though it were a list/tuple of strings.
Internally it falls back to the settings.table_style value, so we'll use
that.
Work done with @stefanv.
=> change the way we set booktabs to use the internal mechanism

publisher/README.md
At the request of the excellent @mpacer, adds some background info
on DOIs, ISSN, and Crossref to publisher/README.
=> DOC: doitools and crossref metadata
