scipy-conference/scipy_proceedings

papers/00_vanderwalt/00_vanderwalt.rst, publisher/writer/__init__.py
ref #120
This PR changes the author-institution data structure into many-to-many mapping, so that each author can have multiple affiliations without redundant \thanks clauses.
I've only tested this with pdf output on the sample doc (with some modifications to make sure it works).
=> added support for multiple institution affiliations per author

publisher/build_paper.py
Added parens to the print statements so that it would be compatible with both python 3 and python 2.
=> Fixed print statements in build_paper.py to be python 3 compatible

publisher/writer/__init__.py
Added a copyright_holder tag that can be used to replace the authors' copyright with an author-defined one.
Sample usage would be:
:author: Joe Author
:email: joe@author.org
:copyright_holder: My Company, Inc.
=> [Issue 169] Copyright Holder Different Than Author

reviews/invite-reviewer.txt.in
First draft of the reviewer mail, this mail is intended to go out to the whole list of reviewers and only those who respond that they are interested in reviewing this year will receive further more detailed communications.
I have tried an informal approach, let me know of any thoughts, in particular I was thinking if there needs to be additional information that I am missing or if the style needs to be a bit more formal.
=> 2016 reviewer mail

publisher/build_paper.py, publisher/build_papers.py, publisher/build_template.py, publisher/mail/_mailer.py, publisher/mail/mail_authors.py, publisher/mail/mail_reviewers.py, publisher/options.py, publisher/writer/__init__.py
This fixes the errors that arise when running `make_paper.sh` under Python 3; there are still some issues related to `tempita` that prevent the proceedings from building correctly, but this is a start at least.
cc: @stefanv
=> Python 3 compatibility for building papers

README.md, publisher/writer/__init__.py
This is a proposal to change the default BibTeX style used in the SciPy proceedings to `alphaurl`.
The `alpha` BibTeX style currently used in the SciPy proceedings does not support the `doi` and `url` BibTeX fields. The [suggested review criteria](https://github.com/scipy-conference/scipy_proceedings/blob/master/review_criteria.md) as well as major publishers (e.g. [Elsevier](https://www.elsevier.com/journals/neurocomputing/0925-2312/guide-for-authors) and [IEEE](http://www.ieee.org/documents/ieeecitationref.pdf)) encourage the use of the DOI. Thus, the BibTeX style used in the SciPy proceedings should be changed to one that supports the `doi` and `url` fields.
The `alphaurl` BibTeX style from the [urlbst](https://www.ctan.org/pkg/urlbst) project is a minimum modification of the `alpha` …
=> Proposal: Change default BibTeX style from alpha to alphaurl.

publisher/build_paper.py
This may be too strict. But it is never bad to be too strict.
This should give an error on #192 (instead of giving question marks)
=> Publisher dies if natbib complains error.

publisher/build_paper.py
(re-opening as a PR to master instead of 2016)
6794ca5 restored some Python 3-incompatible code that was fixed in #182. This restores the correct version which works under 2 and 3.
```
scipy_proceedings git:(2016) ✗ ./make_paper.sh papers/brett_naul
Building: brett_naul
*** Warning: /Users/brettnaul/Dropbox/Documents/scipy_proceedings/publisher/../output/brett_naul/paper_stats.json does not exist.
Traceback (most recent call last):
File "publisher/build_paper.py", line 225, in <module>
build_paper(paper_id)
File "publisher/build_paper.py", line 211, in build_paper
pdflatex_stdout = tex2pdf(out_path)
File "publisher/build_paper.py", line 113, in tex2pdf
out, retry = tex2pdf_singlepass(out_path)
File "publisher/build_paper.py", line 172, in tex2pdf_singlepass
if err or 'Error' in out_bib: …
```
=> Fix Python3 error introduced in 6794ca5

publisher/build_paper.py
This version properly handles Latin-1 characters, unlike #222.
=> Better version of Python 3 fix: avoid decoding

publisher/build_paper.py
Print the errors such that the user is not scratching their head about what went wrong with their bibtex source file.
=> Print bibtex errors in case of an error.

README.md, review_criteria.md, reviews/invite-reviewer.txt.in, scipy_proc.json
@katyhuff mentioned this needed to be done, should have gotten everything. 
Also unless new content is addressed a simple find and replace can work for 2017 → 2018 next year (because there were no conflicting instances of 2017).
=> 2016 --> 2017

publisher/build_paper.py, publisher/build_papers.py, publisher/build_template.py, publisher/conf.py
This doesn't do anything to change binary files, but I tried to exhaustively find anywhere the code is reading or writing a file using the default encoding and ensure that it's instead going to follow utf-8. 
That should address the ascii codec problems that people are dealing with.
Because this should directly address our build issues on the server I'm going to merge this immediately.
=> explicitly declare encoding on file reads and writes

publisher/_static/scipy.sty
This improves `scipy.sty` by making sure all single quotation marks in code are not curly, and thus both appear and also copy correctly. It also adds the `amssymb` package to provide some additional math symbols. I added some custom LaTeX in my paper submission (#285) to accomplish this; if `scipy.sty` is improved, then that custom LaTeX would no longer be necessary.
=> Improve `scipy.sty` (no curly quotes in code, more math symbols)

publisher/_templates/copyright.tex.tmpl
This PR corrects two keyword arguments in the template file in `_templates/copyright.tex.tmpl` to match the metadata we currently store in `scipy_proc.json`.
=> Fix : allows more than two editors on copyright page

publisher/_templates/students.tex.tmpl, scipy_proc.json
This includes dates, editors, and organizers, but does not include the scholarship recipients -- I am waiting to hear back about a list of these.
=> Fix : updates proceedings metadata for 2017

publisher/build_papers.py
A bug arose related to including files and relative paths in #283 when running `make proceedings-html`. 
This arose in part because of the working directory from which the `build_paper` command was run when using `/make_paper.sh`. This hackily normalises that by changing the directory only for the purposes of running that command.
Thanks to @jhamrick for quick thinking on this one.
I'm going to merge this quickly so that I can make the current proceedings now.
=> change build_papers to build papers in the same directory that ./make_paper.sh did for path consistency

scipy_proc.json
Updates the ordinal in scipy_proc.json; closes #316. Thanks to @narendramukherjee for reporting the :bug: !
=> FIX : updates "15th" to "16th" for conference ordinal

publisher/Makefile
Primarily this just makes it possible to zip up the html directory 
This adds two variables (name of zip file and a directory to be the base directory when the zipfile is unpacked) that are compatible with the way that the http://conference.scipy.org/proceedings site likes to have things named & a name for the zip file.
It will need to be updated just like any other manually specified string relevant to the date. 
But this should avoid the issues that came up a few times when I was trying to build it manually before the conference.
=> add zip command to Makefile to ease deployment

publisher/xreftools.py
xref documentation says metametadata timestamp is arbitrary floating point number and test submissions pass with floats, but actual submission process fails if not integer
=> FIX: changes timestamp from float to int

publisher/xreftools.py
There is a typo in the function that generates the paper endpoints for the DOI metadata which currently omits the "l" in "html".
=> FIX: adds 'l' to 'html' for conference paper web page

publisher/build_papers.py, publisher/mail/_mailer.py, publisher/mail/mail_dois.py, publisher/mail/templates/doi-notification.txt.tmpl, publisher/xreftools.py, scipy_proc.json
This PR modifies `build_papers` such that the generated DOIs end up in `toc.json` and `scipy_proc.json` whenever the proceedings for the conference are built. It adds a script that hooks into the existing email notification infrastructure, and fills in a simple template with authors, email addresses, and DOIs for each paper. The generated text looks like this:
```
From: dniederhut@enthought.com
Subject: Your SciPy 2017 Paper DOI
To: jj@rome.it, mark37@rome.it, millman@rome.it, brutus@rome.it
Cc: katyhuff@gmail.com, dalippa@gmail.com, dniederhut@enthought.com, mpacer@berkeley.edu
MIME-Version: 1.0
Content-Type: text/plain
Dear Gaius Caesar, Mark Anthony, Jarrod Millman, and Brutus,
Your paper from the 16th Python in Science Conference titled “A Numerical Perspective to Terraforming a …
```
=> NEW: script to autogenerate DOI announcement emails

papers/horea-ioan_ioanas/paper.rst, papers/ingo_heimbach/paper.rst, papers/jaime_arias/paper.rst, papers/joseph_hellerstein/scisheets.rst, papers/klaus_greff/paper.rst, papers/michael_beyeler/michael_beyeler.rst, papers/michael_lange/michael_lange.rst, papers/narendra_mukherjee/00_vanderwalt.rst, papers/oleksandr_pavlyk/optimizations.rst, papers/will_barnes/paper.rst, publisher/writer/__init__.py
This is one of the last steps we need to complete before we can release the papers. 
I did this by hand, so there could be errors. 
But, I think all of the remaining papers that don't have video links (after this PR is merged) are papers associated with poster presentations (and therefore have no video).
=> update video links for all authors to SciPy2017 videos, remove links to non SciPy2017 videos

papers/00_vanderwalt/00_vanderwalt.rst, publisher/build_paper.py, publisher/writer/__init__.py
Basically the problem was that `self.out` was a record of the whole document up until that point, and so rather than stripping the unnecessary `%` from the footnote that was being created (which was why the line was originally introduced in https://github.com/scipy-conference/scipy_proceedings/commit/7cb4c6a8f169b3667ba6326877cbb0bf98bd9556), it was replacing it with the second element of the complete document. 
In this case it was replacing it with the header, which was causing LaTeX to break when it tried to define commands more than once.
a debugging session with @stefanv and @Carreau helped me figure this one out
=> Fixing docutils 0.14 build issues: footnotes & code in captions

papers/00_bibderwalt/00_bibderwalt.rst, papers/00_bibderwalt/mybib.bib, publisher/writer/__init__.py
This creates a linked doi for the associated doi in the bibliography entry: at `http://dx.doi.org/<doi>`
So in this case, it is http://dx.doi.org/10.1017/CBO9780511808432. 
I also added "documentation" to the 00_bibderwalt example.
Also, I reverted 5dd888dd4fe72d9b168e33a05758bbf8f368c68e
`self.non_breaking_paragraph` isn't a docutils feature, but it is a custom feature we use in a super roundabout fashion. 
Basically we have an elif looking for  `self.non_breaking_paragraph` in `self.visit_paragraph()`. The only point of that elif is to preëmptively catch stuff before it had newlines added to it in https://github.com/scipy-conference/scipy_proceedings/blob/82253931a114463b31856f93169b5a65553eae3a/publisher/writer/__init__.py#L306-L310
There is probably a better way to implement this, but …
=> add doi example to 00_bibderwalt citation

publisher/_templates/header.html.tmpl
It looks like google scholar may not be correctly indexing
papers by `<meta name=citation_conference_title>`. This adds
`<meta name=citation_journal_title>` with the same content.
Closes #299.
=> BUG: adds citation_journal_title meta tag
